### ISSUE TITLE
Incorrect help file output path

### ISSUE THREAD

**Issue by demianmnave** [PlagueHO/LoopbackAdapter#22]
Hi,

There is an error in the _Compile_Help_ workflow in [build.yaml](https://github.com/PlagueHO/LoopbackAdapter/blob/main/build.yaml) on the _main_ branch due to `$ProjectName` being empty when called.

It appears that the XML file should be placed in _LoopbackAdapter/&lt;version&gt;_, but it ends up one level higher, under _LoopbackAdapter_.

It also can lead to the file going into a wonky path if the `OutputDirectory` parameter to _build.ps1_ points to a non-empty directory, and if the `Tasks` parameter is specified to skip the _Clean_ task (e.g. to put build outputs from several projects into a single root).

Adding the following lines before `if ([System.String]::IsNullOrEmpty($ENV:ModuleVersion))`  corrects the problem:

```
if ([System.String]::IsNullOrEmpty($ProjectName))
{
          $ProjectName = Get-ProjectName -BuildRoot $BuildRoot
}
```

Finally, I started preparing a pull request, but discovered that the _dev_ branch mentioned in [Contributing.md](https://github.com/PlagueHO/LoopbackAdapter/blob/main/.github/CONTRIBUTING.md) doesn't actually exist to receive it. Is this worthy of a separate issue?

Thanks, Demian

**Comment by PlagueHO** [comment]
Hi @demianmnave - I found this problem as well over in one of my other modules, but haven't had time to port the fix. If you want you can port it over from here: https://github.com/PlagueHO/CosmosDB/pull/406/files

I added a bunch of verbose information to help sort this in future.

FYI, I'm also planning to update to main when I have time, but it requires a few other bits and pieces - so I'll correct Contributing.md then as well :grin:

**Comment by demianmnave** [comment]
Can do. Pull request to _main_?

**Comment by PlagueHO** [comment]
Just submit the pull request to master for now if you like. I'll do the change to main later.
