### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by PlagueHO** [PlagueHO/LoopbackAdapter#23]
As per [this statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

Copy the changes as per https://github.com/PlagueHO/CosmosDB

**Comment by demianmnave** [comment]
What am I missing? The default branch already shows up in GitHub as _main_.

**Comment by PlagueHO** [comment]
Doh! Fail- I'd already renamed it. Blame a long week.

**Comment by demianmnave** [comment]
👍
