### ISSUE TITLE
Error using 32-bit PowerShell on x64 bit OS

### ISSUE THREAD

**Issue by marckassay** [PlagueHO/LoopbackAdapter#4]
When I call New-LoopbackAdapter, I get the following error:
`"The new Loopback Adapter was not found."`

This is caused by this line:
`if ($ENV:PROCESSOR_ARCHITECTURE -like '*64')`

As of .Net 4.0, I believe the following will work for Mac and Linux:
`if ([Environment]::Is64BitOperatingSystem -eq $True)`

**Comment by PlagueHO** [comment]
Fixed by #5
